version: BUILD{build}

image: Visual Studio 2019
shallow_clone: true

configuration:
- Debug
- Release

before_build:
  - nuget restore

build:
  project: Quasar.sln
  parallel: true
  verbosity: minimal

test_script:
  - dotnet test Quasar.Common.Tests/Quasar.Common.Tests.csproj --no-build --configuration %CONFIGURATION%

artifacts:
- path: Bin
  name: binaries